#!/bin/bash

function up() {
    echo "Starting containers..."
    docker-compose up "$@"
}

function down() {
    echo "Stopping containers..."
    docker-compose down
}

function exec() {
    docker-compose exec web python manage.py "$@"
}

command="$1"
shift
case "$command" in
    up)
        up "$@"
        ;;
    down)
        down
        ;;
    *)
        exec "$@"
        ;;
esac
